### ISSUE TITLE
关于参数的补充

### ISSUE THREAD

**Issue by Maze-is-moon** [WhatETE/QQessence#1]
项目中的p_skey 和skey 这两个参数，作者给的方式是：通过fiddler，打开群精华获取。
这里提供另一个思路：
登录qq群官网，https://qun.qq.com/ ， 从cookie中获取这两个参数。
具体可参考https://www.52pojie.cn/thread-835096-1-1.html

**Comment by WhatETE** [comment]
感谢完善
